### ISSUE TITLE
Broken on Sphinx 7x

### ISSUE THREAD

**Issue by Amourspirit** [MrDogeBro/sphinx_rtd_dark_mode#42] opened 2023-07-06 19:48 UTC
Sphinx 7x no longer uses `style`

```
Theme error:
An error happened in rendering the page index.
Reason: UndefinedError("'style' is undefined")
```

See  Remove deprecated style key for HTML templates [#11381](https://github.com/sphinx-doc/sphinx/pull/11381)

See Also
https://github.com/readthedocs/sphinx_rtd_theme/pull/1467/files/b2b3c60096f6f70216c574bf863c7ff2e1a4f732#diff-0f78e90ab4f9d57568ee00cdd81040c20bfbdaf7f19169e82e10a5e11e249052

**Comment by MrDogeBro** [comment] 2023-09-15 01:32
@Amourspirit I am pretty sure that this is an issue with another package and not the dark mode. The dark mode does not use the style or styles property as you described in any way. Furthermore, I am not able to replicate the results on my end; my test docs build fine on Sphinx v7 without any issues. I will be closing this issue shortly unless it can be definitively determined that this extension is the cause of the error and not another one of the extensions you have installed with your project.

**Comment by MrDogeBro** [comment] 2023-09-27 00:54
Closing this issue now. Please reopen if it is a problem.

**Closed by MrDogeBro** 2023-09-27 00:54 UTC
Labels: status/blocked
